### ISSUE TITLE
info

### ISSUE THREAD

**Issue by francescomadeo** [luc-github/DUE-RADDS-GLCD#2]
Your change is now also available again on marlinkimbra

**Comment by luc-github** [comment]
My changes on marlinkimbra ?

**Comment by francescomadeo** [comment]
Excuse me, I explain in the wrong, your TWO-RADDS-LCD now Added natively also on marlinkimbra

**Comment by luc-github** [comment]
italiano? la traduzione di Google non è corretta ^_^ "DUE" = "DUE" non è "TWO"

Grazie mille, non lo ho veduto
Perdonna me, fa molto tempo che non ho parlato italiano

**Comment by francescomadeo** [comment]
no problem excuse you for the English! I just wanted to report this thing

**Comment by luc-github** [comment]
non ti preoccupare, sei molto gentile :smile:

**Comment by francescomadeo** [comment]
If you enter in the readme compatibility with marlinkimbra we would like, thanks! ;-)

**Comment by luc-github** [comment]
Ok will do - thank you

**Comment by francescomadeo** [comment]
thanks very kind!

**Comment by luc-github** [comment]
can you give me the link ? I do not find compatibility section

**Comment by francescomadeo** [comment]
marlinkimbra.it

**Comment by luc-github** [comment]
OK - I was checking the github, thank you

**Comment by Ludwig11** [comment]
Hi, a little bit late, but can you explain how you made the cables, because some connections go to both places, the SD Card and the LCD.
Thank you

**Comment by luc-github** [comment]
what you mean ?
https://github.com/luc-github/DUE-RADDS-GLCD/blob/master/Images/RADDS%20-%20REPRAPFULLGRAPHICLCDV2.png?raw=true

A goes to A, B goes to B, etc

**Comment by Ludwig11** [comment]
Yes, thats clear so far. On the photo it seems that you have two separate flat ribbon cables where Ext 1 is connected to the LCD connector on the radds board and Ext 2 is connected to the SD card connector. But H and J are on Ext 2 and go to the LCD connector of the board. So this implies, that you have 2 single cables for these ports H and J. I don't know if I made clear what I mean...

**Comment by luc-github** [comment]
the picture is the RADDS specific text lcd so ribon follow the connectors as it is designed for this LCD and connectors

for the GLCD you need to cross the connections from one connector to another when needed as I describe

**Comment by luc-github** [comment]
@cicciom I just realized the reference to Marlinkimbra was not applied - now it is done, really sorry for the delay - very nice FW I love the Nextion implementation

**Comment by Ludwig11** [comment]
Okay, that is what I supposed. To cross the cables. I am not very firm in electronics.
Thank youLudwig


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Luc <notifications@github.com> 
Datum: 28.01.17  15:58  (GMT+01:00) 
An: luc-github/DUE-RADDS-GLCD <DUE-RADDS-GLCD@noreply.github.com> 
Cc: Ludwig11 <info@fxdigital.de>, Comment <comment@noreply.github.com> 
Betreff: Re: [luc-github/DUE-RADDS-GLCD] info (#2) 

the picture is the RADDS specific text lcd so ribon follow the connectors as it is designed for this LCD and connectors
for the GLCD you need to cross the connections from one connector to another when needed

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/luc-github/DUE-RADDS-GLCD","title":"luc-github/DUE-RADDS-GLCD","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/luc-github/DUE-RADDS-GLCD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@luc-github in #2: the picture is the RADDS specific text lcd so ribon follow the connectors as it is designed for this LCD and connectors\r\n\r\nfor the GLCD you need to cross the connections from one connector to another when needed"}],"action":{"name":"View Issue","url":"https://github.com/luc-github/DUE-RADDS-GLCD/issues/2#issuecomment-275852784"}}}
